const express = require('express');
const router  = express.Router();
const UserControll = require('../controllers/userControllers/UserControll')
const studentsController = require('../controllers/studentsController/studentsController')
const MasterController = require('../controllers/MasterController/MasterController');
const { employeeApi, getEmployeeApi, getEmployeeByIdApi, employeewithimageApi, getemployeeImageUpdateApi, getEmployeeSomeApi, getEmployeeProfileApi } = require('../controllers/EmployeeController/EmployeeController');



//user

router.post("/otp", UserControll.otp )
router.post("/loginuser", UserControll.userLogin )
router.post("/registeruser", UserControll.userRegister )

//students

router.post("/getStudentOneinfoApi", studentsController.getStudentOneinfoApi)
router.post("/getDataStudentsApi", studentsController.getDataStudentsApi)
router.post("/getStudentByBranchFeeApi", studentsController.getStudentByBranchFeeApi)
router.post("/studentLogin", studentsController.studentLogin)
router.post("/StudentsApi", studentsController.studentsApi )
router.post("/getStudentUpdateApi", studentsController.getStudentUpdateApi )
router.post("/StudentUpdateWithoutimageApi", studentsController.StudentUpdateWithoutimageApi )
router.post("/studentFeeApi", studentsController.studentsFeeApi )
router.post("/getStudentsApi", studentsController.getStudentsApi )
router.get("/getStudentsPageApi", studentsController.getStudentsPageApi )
router.post("/displayStudentsClassBy", studentsController.displayStudentsClassBy )
router.post("/studentAttendance", studentsController.studentAttendance )
router.post("/getstudentsFeeApi", studentsController.getstudentsFeeApi )
router.post("/getstudentsFeebyclassApi", studentsController.getstudentsFeebyclassApi )
router.post("/addStudentsFeeApi", studentsController.addStudentsFeeApi )
router.post("/getStudentsByClassApi", studentsController.getStudentsByClassApi )
router.post("/getProfilestudentsFeeApi", studentsController.getProfilestudentsFeeApi )
/* router.get("/uploadFileApi", studentsController.uploadExcelFile )
router.get("/downloadApi", studentsController.downloadApi )
 */

// master
router.post("/getSubjectByClassApi", MasterController.getSubjectByClassApi)
router.post("/feefrequencyControlApi", MasterController.feefrequencyControlApi)
router.post("/sectionControlApi", MasterController.sectionControlApi)
router.post("/sectionUpdateApi", MasterController.sectionUpdateApi)
router.post("/classControlApi", MasterController.classControlApi)
router.post("/classUpdateApi", MasterController.classUpdateApi)
router.post("/getBranchControlApi", MasterController.getBranchControlApi)
router.post("/addBranchUpdateApi", MasterController.addBranchUpdateApi)
router.post("/addBranchApi", MasterController.addBranchApi)
router.get("/getBranchApi", MasterController.getBranchApi)
router.post("/getBranchOneApi", MasterController.getBranchOneApi)
router.post("/getBranchGroupIdApi", MasterController.getBranchGroupIdApi)
router.post("/getSessionByBranchIdApi", MasterController.getSessionByBranchIdApi)
router.post("/feeheadApi", MasterController.feeHeadApi)
router.post("/getfeeHeadApi", MasterController.getfeeHeadsApi)
router.post("/feeheadUpdateApi", MasterController.feeheadUpdateApi)
router.post("/getAllfeeHeadApi", MasterController.getAllfeeHeadsApi)
router.post("/sessionControlApi", MasterController.sessionControlApi)
router.post("/sessionApi", MasterController.sessionApi)
router.post("/sessionUpdateApi", MasterController.sessionUpdateApi)
router.get("/getSessionApi", MasterController.getSessionApi)
router.post("/classApi", MasterController.classApi)
router.post("/getClassApi", MasterController.getClassApi)
router.post("/getSectionApi", MasterController.getSectionApi)
router.post("/SectionApi", MasterController.SectionApi)
router.post("/classDetailsApi", MasterController.ClassDetailApi)
router.post("/ClassDetailUpdateApi", MasterController.ClassDetailUpdateApi)
router.post("/getclassDetailApi", MasterController.getClassDetailApi)
router.post("/getClassDetailSomeApi", MasterController.getClassDetailSomeApi)
router.post("/getClassDetailApiByclass", MasterController.getClassDetailApiByclass)
router.post("/subjectHeadApi", MasterController.subjectHeadApi)
router.get("/getAllsubjectHeadApi", MasterController.getAllsubjectHeadApi)
router.post("/getsubjectHeadApi", MasterController.getsubjectHeadApi)
router.post("/getsubjectheadtosubjectApi", MasterController.getsubjectheadtosubjectApi)
router.post("/subjectApi", MasterController.subjectApi)
router.post("/getsubjectApi", MasterController.getsubjectApi)
router.get("/getAllsubjectApi", MasterController.getAllsubjectApi)
router.post("/subjecttoHeadApi", MasterController.subjecttoHeadApi)
router.post("/getSubjectWithSubjecttoheadApi", MasterController.getSubjectWithSubjecttoheadApi)
router.get("/getAllsubjecttoHeadApi", MasterController.getAllsubjecttoHeadApi)
router.post("/getsubjecttoHeadApi", MasterController.getsubjecttoHeadApi)
router.post("/FeeFrequencyApi", MasterController.FeeFrequencyApi)
router.post("/getFeeFrequencyApi", MasterController.getFeeFrequencyApi)
router.post("/getAllFeeFrequencyApi", MasterController.getAllFeeFrequencyApi)
router.post("/feefrequencyUpdateApi", MasterController.feefrequencyUpdateApi)
router.post("/subjectheadUpdateApi", MasterController.subjectheadUpdateApi)
router.post("/subjectUpdateApi", MasterController.subjectUpdateApi)
router.post("/subjectToassignUpdateApi", MasterController.subjectToassignUpdateApi)
router.post("/TimeSchedule", MasterController.TimeSchedule)
router.post("/gettimescheduleApi", MasterController.gettimescheduleApi)
router.post("/gettimetableperiodApi", MasterController.gettimetableperiodApi)
router.post("/TimeScheduleUpdate", MasterController.TimeScheduleUpdate)

//teacher
router.post("/getEmployeeSomeApi", getEmployeeSomeApi)
router.post("/getEmployeeApi", getEmployeeApi)
router.post("/getEmployeeProfileApi", getEmployeeProfileApi)
router.post("/employeeApi",employeeApi)
router.post("/employeewithimageApi",employeewithimageApi)
router.post("/getemployeeImageUpdateApi",getemployeeImageUpdateApi)
router.post("/TimeTableApi",MasterController.TimeTableApi)
router.post("/TimeTableUpdateApi",MasterController.TimeTableUpdateApi)
router.post("/getTimeTableApi",MasterController.getTimeTableApi)
router.post("/getClassDetailByClassApi",MasterController.getClassDetailByClassApi)
router.post("/getEmployeeTimeTableApi",MasterController.getEmployeeTimeTableApi)
router.post("/getStudentTimeTbaleApi",MasterController.getStudentTimeTbaleApi)

module.exports=router